services:
  - type: web
    name: almatymeetups-telegram-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: TARGET_GROUP_ID
        sync: false
      - key: DATABASE_URL
        value: sqlite:///data/bot_database.db
